// Single source of truth for all lesson metadata.
// Keyed by slug (part/name). Content files (description.html, .sv, images)
// stay co-located in each lesson directory and are loaded lazily on demand.
export default {
  // ── SystemVerilog Basics ───────────────────────────────────────────────────
  'sv/welcome':              { title: 'Welcome',                                      focus: '/src/top.sv' },
  'sv/modules-and-ports':    { title: 'Modules and Ports',                            focus: '/src/adder.sv' },
  'sv/data-types':           { title: 'Data Types',                                   focus: '/src/data_types.sv' },
  'sv/always-comb':          { title: 'always_comb and case',                         focus: '/src/mux.sv' },
  'sv/priority-enc':         { title: 'Priority Encoder',                             focus: '/src/priority_enc.sv' },
  'sv/events':               { title: 'Events',                                        focus: '/src/event_sync.sv' },
  'sv/always-ff':            { title: 'Flip-Flops with always_ff',                    focus: '/src/sram_core.sv' },
  'sv/counter':              { title: 'Up-Counter',                                   focus: '/src/counter.sv' },
  'sv/parameters':           { title: 'Parameters and localparam',                    focus: '/src/sram.sv' },
  'sv/packed-structs':       { title: 'Packed Structs and Unions',                    focus: '/src/mem_cmd.sv' },
  'sv/interfaces':           { title: 'Interfaces and modport',                       focus: '/src/mem_if.sv' },
  'sv/tasks-functions':      { title: 'Tasks and Functions',                          focus: '/src/tb.sv' },
  'sv/enums':                { title: 'typedef enum',                                 focus: '/src/status.sv' },
  'sv/fsm':                  { title: 'Two-Always Moore FSM',                         focus: '/src/mem_ctrl.sv' },
  'sv/covergroup-basics':    { title: 'covergroup and coverpoint',                    focus: '/src/cov_intro.sv' },
  'sv/coverpoint-bins':      { title: 'Bins and ignore_bins',                         focus: '/src/cov_bins.sv' },
  'sv/cross-coverage':       { title: 'Cross coverage',                               focus: '/src/cov_cross.sv' },

  // ── SystemVerilog Assertions ───────────────────────────────────────────────
  'sva/concurrent-sim':      { title: 'Concurrent Assertions in Simulation',          focus: '/src/monitor.sv',         runner: null },
  'sva/vacuous-pass':        { title: 'Vacuous Pass',                                 focus: '/src/vacuous.sv' },
  'sva/isunknown':           { title: '$isunknown — Detecting X and Z',               focus: '/src/xcheck.sv' },
  'sva/immediate-assert':    { title: 'Immediate Assertions',                         focus: '/src/fifo_checker.sv',    runner: 'bmc' },
  'sva/sequence-basics':     { title: 'Sequences and Properties',                     focus: '/src/grant_check.sv',     runner: 'bmc' },
  'sva/implication':         { title: 'Implication: |-> and |=>',                     focus: '/src/implication.sv',     runner: 'bmc' },
  'sva/formal-intro':        { title: 'Bounded Model Checking',                       focus: '/src/top.sv',             runner: 'bmc' },
  'sva/clock-delay':         { title: 'Clock Delay ##m and ##[m:n]',                  focus: '/src/delay_check.sv',     runner: 'bmc' },
  'sva/rose-fell':           { title: '$rose and $fell',                              focus: '/src/edge_check.sv',      runner: 'bmc' },
  'sva/req-ack':             { title: 'Request / Acknowledge',                        focus: '/src/req_ack.sv',         runner: 'bmc' },
  'sva/consecutive-rep':     { title: 'Consecutive Repetition [*m]',                  focus: '/src/hold_check.sv',      runner: 'bmc' },
  'sva/nonconsec-rep':       { title: 'Goto Repetition [->m]',                        focus: '/src/multi_ack.sv',       runner: 'bmc' },
  'sva/nonconsec-eq':        { title: 'Non-Consecutive Equal Repetition [=m]',        focus: '/src/multi_ack2.sv',      runner: 'bmc' },
  'sva/throughout':          { title: 'throughout — Stability During a Sequence',     focus: '/src/spi_check.sv',       runner: 'bmc' },
  'sva/sequence-ops':        { title: 'Sequence Composition: intersect, within, and, or', focus: '/src/bus_check.sv',  runner: 'bmc' },
  'sva/stable-past':         { title: '$stable and $past',                            focus: '/src/stable_check.sv',    runner: 'bmc' },
  'sva/changed':             { title: '$changed and $sampled',                        focus: '/src/toggle_check.sv',    runner: 'bmc' },
  'sva/disable-iff':         { title: 'disable iff — Reset Handling',                 focus: '/src/reset_check.sv',     runner: 'bmc' },
  'sva/abort':               { title: 'Aborting Properties: reject_on and accept_on', focus: '/src/abort_check.sv',    runner: 'bmc' },
  'sva/cover-property':      { title: 'cover property',                               focus: '/src/bus_check.sv',       runner: 'bmc' },
  'sva/local-vars':          { title: 'Local Variables in Sequences',                 focus: '/src/pipeline_check.sv',  runner: 'bmc' },
  'sva/onehot':              { title: '$onehot, $onehot0, $countones',                focus: '/src/arbiter_check.sv',   runner: 'bmc' },
  'sva/triggered':           { title: '.triggered — Sequence Endpoint Detection',     focus: '/src/trigger_check.sv',   runner: 'bmc' },
  'sva/checker':             { title: 'The checker Construct',                        focus: '/src/top.sv',             runner: 'bmc' },
  'sva/recursive':           { title: 'Recursive Properties',                         focus: '/src/lock_check.sv',      runner: 'bmc' },
  'sva/formal-assume':       { title: 'assume property',                              focus: '/src/top.sv',             runner: 'both' },
  'sva/always-eventually':   { title: 'always and s_eventually',                      focus: '/src/liveness.sv',        runner: 'bmc' },
  'sva/until':               { title: 'until and s_until',                            focus: '/src/hold_check.sv',      runner: 'bmc' },
  'sva/lec':                 { title: 'Logical Equivalence Checking',                 focus: '/src/top.sv',             runner: 'lec', module1: 'Spec', module2: 'Impl' },

  // ── UVM ───────────────────────────────────────────────────────────────────
  'uvm/reporting':           { title: 'The First UVM Test',                           focus: '/src/my_test.sv' },
  'uvm/seq-item':            { title: 'Sequence Items',                               focus: '/src/mem_item.sv' },
  'uvm/sequence':            { title: 'Sequences',                                    focus: '/src/mem_seq.sv' },
  'uvm/driver':              { title: 'The Driver',                                   focus: '/src/mem_driver.sv' },
  'uvm/constrained-random':  { title: 'Constrained-Random Scenarios',                 focus: '/src/mem_test.sv' },
  'uvm/monitor':             { title: 'Monitor and Scoreboard',                       focus: '/src/mem_scoreboard.sv' },
  'uvm/env':                 { title: 'Environment and Test',                         focus: '/src/mem_env.sv' },
  'uvm/covergroup':          { title: 'Functional Coverage',                          focus: '/src/mem_coverage.sv' },
  'uvm/cross-coverage':      { title: 'Cross Coverage',                               focus: '/src/mem_coverage.sv' },
  'uvm/coverage-driven':     { title: 'Coverage-Driven Verification',                 focus: '/src/mem_test.sv' },
  'uvm/factory-override':    { title: 'Factory Overrides',                            focus: '/src/mem_test_corner.sv' },

  // ── MLIR & CIRCT ──────────────────────────────────────────────────────────
  'mlir/intro':    { title: 'What is MLIR?',                    focus: '/src/adder.mlir' },
  'mlir/comb':     { title: 'The comb Dialect',                 focus: '/src/priority_enc.mlir' },
  'mlir/seq':      { title: 'The seq Dialect: Registers',       focus: '/src/sram_core.mlir' },
  'mlir/lowering': { title: 'The Lowering Pipeline',            focus: '/src/lowering.mlir' },

  // ── cocotb ────────────────────────────────────────────────────────────────
  'cocotb/first-test':           { title: 'Your First cocotb Test',    runner: 'cocotb', focus: '/src/adder.sv' },
  'cocotb/clock-and-timing':     { title: 'Clock and Timing',          runner: 'cocotb', focus: '/src/counter.sv' },
  'cocotb/edge-triggers':        { title: 'Edge Triggers and Clock',   runner: 'cocotb', focus: '/src/reg_en.sv' },
  'cocotb/clockcycles-patterns': { title: 'ClockCycles and Patterns',  runner: 'cocotb', focus: '/src/pulse_counter.sv' },
};
